/*
  Warnings:

  - You are about to drop the `user` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE `user`;

-- CreateTable
CREATE TABLE `PER_PROFILE` (
    `PER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PER_EMP_NUMBER` VARCHAR(191) NOT NULL,
    `POS_ID` INTEGER NOT NULL,
    `PREFIX_ID` INTEGER NOT NULL,
    `PER_FNAME_TH` VARCHAR(191) NOT NULL,
    `PER_MNAME_TH` VARCHAR(191) NOT NULL,
    `PER_LNAME_TH` VARCHAR(191) NOT NULL,
    `PER_FNAME_EN` VARCHAR(191) NOT NULL,
    `PER_MNAME_EN` VARCHAR(191) NOT NULL,
    `PER_LNAME_EN` VARCHAR(191) NOT NULL,
    `GENDER_ID` INTEGER NOT NULL,
    `PER_TYPE_ID` INTEGER NOT NULL,
    `RACE_ID` INTEGER NOT NULL,
    `NATION_ID` INTEGER NOT NULL,
    `RELIGION_ID` INTEGER NOT NULL,

    PRIMARY KEY (`PER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
