-- AlterTable
ALTER TABLE `m_position` MODIFY `createDate` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateDate` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `isActive` BOOLEAN NULL DEFAULT true;

-- AlterTable
ALTER TABLE `per_profile` MODIFY `createDate` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `updateDate` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- CreateTable
CREATE TABLE `M_POSITION_LEVEL` (
    `posLevelId` INTEGER NOT NULL AUTO_INCREMENT,
    `posLevelTh` VARCHAR(191) NULL,
    `posLevelEn` VARCHAR(191) NULL,
    `createDate` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updateDate` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createBy` INTEGER NULL,
    `updateBy` INTEGER NULL,
    `isActive` BOOLEAN NULL DEFAULT true,
    `deletedAt` DATETIME(3) NULL,

    PRIMARY KEY (`posLevelId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
